//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLink.Business.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLink.Business.Common.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Център.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клуб.
        /// </summary>
        public static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треньор.
        /// </summary>
        public static string Coach {
            get {
                return ResourceManager.GetString("Coach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Събития.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плеймейкър.
        /// </summary>
        public static string Guard {
            get {
                return ResourceManager.GetString("Guard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} см..
        /// </summary>
        public static string HeightCmFormat {
            get {
                return ResourceManager.GetString("HeightCmFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покани.
        /// </summary>
        public static string Invitations {
            get {
                return ResourceManager.GetString("Invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нямате клуб.
        /// </summary>
        public static string NoClubMessage {
            get {
                return ResourceManager.GetString("NoClubMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Играч.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тежко крило.
        /// </summary>
        public static string PowerForward {
            get {
                return ResourceManager.GetString("PowerForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атакуващ гард.
        /// </summary>
        public static string ShootingGuard {
            get {
                return ResourceManager.GetString("ShootingGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Леко крило.
        /// </summary>
        public static string SmallForward {
            get {
                return ResourceManager.GetString("SmallForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} кг..
        /// </summary>
        public static string WeightKgFormat {
            get {
                return ResourceManager.GetString("WeightKgFormat", resourceCulture);
            }
        }
    }
}
